apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vault-snapshot-cronjob
spec:
  schedule: "@every 12h"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: share
            emptyDir: {}
          containers: 
          - name: upload
            image: amazon/aws-cli:2.2.14
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            args:
            - -ec
            - |
              curl http://consul-consul-server.default.svc.cluster.local:8500/v1/snapshot?dc=vault-kubernetes --output /share/vault-snapshot.tgz
              until [ -f /share/vault-snapshot.tgz ]; do sleep 5; done;
              aws s3 cp /share/vault-snapshot.tgz s3://xti-datavault/vault_xti_snapshot_$(date +"%Y%m%d_%H%M%S").snap;
              aws s3 ls s3://xti-datavault
            env:
            - name: AWS_ACCESS_KEY_ID
              value: "YOUR_AWS_ACCESS_KEY_ID"
            - name: AWS_SECRET_ACCESS_KEY
              value: "YOUR_AWS_SECRET_ACCESS_KEY"
            volumeMounts:
            - mountPath: /share
              name: share
          restartPolicy: Never